### ISSUE TITLE
SEO feature request

### ISSUE THREAD

**Issue by ipears** [neizod/polar#1]
Love this theme, but would love to see implementation fb OG, twitter cards, G author authentication and site verification... ;) so just some extra `<head>` items... would really improve the sharability.

**Comment by neizod** [comment]
Added Facebook OG meta tags, except for `og:image` -- still can't figure out how to auto grab first image within post. And I don't know which Twitter tags should I add more, since the document says it can fallback to OG tags for all of the importance one.

Other than that (G author, site verification), I really had no idea what is it.

Would you like to contribute?

**Comment by ipears** [comment]
Yeah, might try to contribute. Was talking about Google author and Google site verification. 
This might be a good inspiration: https://github.com/johnotander/pixyll/blob/master/_includes/head.html

**Comment by neizod** [comment]
Implemented in: 1b4a73c6bf5cae45af8496f7a19dcd71d2767245, a056396635d27d31f0d652fe1e196d6087371969, dc10eb75ce27c8da5635bb6f12b5e64e6ec8b6d0, and 8dc60e49f48e6562efee1f838d29f77149f3bac8. Please check.

**Comment by neizod** [comment]
Open Graph image is implemented in: a70c8270871e51c96f7f3eb991eb079eb7ed9f9b, 90806453b2a7789696c7959b08c4dbebd36b1696, and 2e8399a919777b4dd84e723d76ec84a99ee52312.

**Comment by neizod** [comment]
Close due to no feedback within a week after commits (reopen is welcome).
